### ISSUE TITLE
ideas

### ISSUE THREAD

**Issue by tora666** [42Tokyo/born2remote-friday-fried-potato#1]
まずは何を作るか!!

**Comment by tora666** [comment]
#### キーワード
- 可視化
- モチベーション
- 息抜き & メンバーを知りたい

#### 問題点
- 他のチームとの差別化
 可視化やモチベーションは他のチームも考えていそう。どう差別化するか。

#### nop
> 技術的に可能だから作るのではなくみんなが「これだ！」っていうものを作って欲しい。

 実現が難しいものでも、今の42やこれからの42に必要なものを選択するべき？

**Comment by nafuka11** [comment]
### 42 Tokyoのリモート学習で感じた課題
- モチベーション管理
- 過疎対策

### 解決案
#### Discord Botの開発
- Botが喋ることで過疎が若干和らぐ（といいな）
- 日毎ランキング（レビュー数など）：競わせることでモチベーションを上げる
- Registerの告知：Register忘れによるモチベーション低下を防ぐ（手動Register警察大変なので……）
- [MEE6にあるランキングカード](https://mee6.xyz/leveling)のような物を作る
   - 何でランキングさせるかが課題。チャットでの発言数はあんまりなので現Discordではこの機能が有効になっていない。
   - 一番楽なのはintraのレベル
   - ランキングにならなくても、コマンド一つでその人のことを知られるといい。
- 以下はモチベーション管理とは別のアイデア
   - user, cursus, project等々をコマンドで取得できるように

**Comment by nafuka11** [comment]
### 課題
- 双方向のコミュニケーションが取りづらい
- ボイスチャンネルで双方向コミュニケーションできるが、参加ハードルが高い
### 解決案
#### Discordのボイスチャンネルをremoっぽく可視化する
- ボイスチャンネルの参加状況をWebアプリで可視化
- 部屋にいる感じを出したい
- ただ可視化するだけだとずっとは見ないので、何かしらの42の機能を追加する必要がある
  - カーソルを当てるとユーザ情報が表示される（idはintraと同じなのでできると思う）
  - 直近のイベントの表示。もしくは通知。

**Comment by Takiwa-i** [comment]
メンバーのことを知るという点では、42tokyo学生だけのsnsとかもありうるかなと思いました（最初期のfacebookのような）

**Comment by nafuka11** [comment]
### 課題
誰がどの程度の進行度なのか分からず、質問がしづらい。
### 解決案
進行度の可視化をする。
- リモートでない
  - clusterマップのフィルタリング
  - projectでフィルタリングできる
- リモートのとき
  - Discordユーザ一覧からフィルタリングする
  - ステータス（オンライン、音声、ボイスチャンネルの所属）を表示する

**Comment by nafuka11** [comment]
### 課題
質問するのが難しい。
- 誰に、何を、どこで質問すればいいか分からない？
### 解決案
質問リコメンドBot。
- 内容：Project名、環境面、うまく言語化できない、etc....
- 回答
  - #ボイスチャンネルに知っている人がいそうです
  - @usernameに聞いてみましょう！
    - @usernameに困っている人がいると通知が行く
  - #チャネル名で聞いてみましょう！

**Comment by nafuka11** [comment]
### 課題
- 今どれくらいclusterに人がいるか知りたい。
  - clusterの時刻ごとにどのくらい人がいるのか？どのような人がいるのか（何かしらの属性）？
- clusterマップになかなかアクセスできない。
### 解決案
- clusterマップ（軽めのやつ）
  - リモートならDiscordのアクティブ表示
  - 時刻ごとの人数表示
- 各自の時間帯アプリに近いかな

**Comment by nafuka11** [comment]
入館カードを家に忘れてしまう。
-> 各自の家にセンサーを取り付ける。

**Comment by nafuka11** [comment]
42 Concielge
- 自分の道案内となるBot
  - 自分の立ち位置がわかる（全体の立ち位置、プロジェクト内の立ち位置）
  - プラスアルファ、質問リコメンドができる
