### ISSUE TITLE
Discord Botのアイコンを作る

### ISSUE THREAD

**Issue by nafuka11** [42Tokyo/born2remote-friday-fried-potato#10]
42 conciergeのBotのavatar（アイコン）を作る。
画像は正方形。
丸く、128px x 128pxに縮小されるようです。

**Comment by tora666** [comment]
![icon1](https://user-images.githubusercontent.com/45866095/80689199-ed455f80-8b07-11ea-888f-1bd24b8a25e7.png)

![icon2](https://user-images.githubusercontent.com/45866095/80689414-490fe880-8b08-11ea-956d-8280436b4d13.png)

![icon3](https://user-images.githubusercontent.com/45866095/80689524-72307900-8b08-11ea-8d5f-e6d14b165995.png)

![icon4](https://user-images.githubusercontent.com/45866095/80689860-e834e000-8b08-11ea-93f6-04a9cd416442.png)

![icon5](https://user-images.githubusercontent.com/45866095/80689615-8eccb100-8b08-11ea-9a9d-ac4824d4e2c4.png)

![icon6](https://user-images.githubusercontent.com/45866095/80690035-2fbb6c00-8b09-11ea-8d5c-097527442128.png)

![icon7](https://user-images.githubusercontent.com/45866095/80690072-3fd34b80-8b09-11ea-9cc2-0ddb0c42dfd4.png)

**Comment by tora666** [comment]
![icon8](https://user-images.githubusercontent.com/45866095/80710212-7620c300-8b29-11ea-8679-46c6698df69b.png)

![icon7](https://user-images.githubusercontent.com/45866095/80710226-7a4ce080-8b29-11ea-8e50-18107a43abbb.png)

![icon9](https://user-images.githubusercontent.com/45866095/80710242-7f119480-8b29-11ea-92d4-92a18278c46f.png)

![icon10](https://user-images.githubusercontent.com/45866095/80710257-833db200-8b29-11ea-82c4-7a19eaefdfe9.png)

![icon11](https://user-images.githubusercontent.com/45866095/80710270-85a00c00-8b29-11ea-8cf8-85caf62003a5.png)

**Comment by nafuka11** [comment]
一番上の
https://user-images.githubusercontent.com/45866095/80689199-ed455f80-8b07-11ea-888f-1bd24b8a25e7.png
に決まりました！
@tora666 さん、ありがとうございます！
