### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by tora666** [42Tokyo/born2remote-friday-fried-potato#2]
おすすめのサイトやこんな感じが見やすいーとかあれば！

**Comment by tora666** [comment]
[MEE6 - The Discord Bot](https://mee6.xyz/levels/71992212115697664)

**Comment by tora666** [comment]
#### 必要な素材
- 全体とプロジェクトでの登録者
- プロジェクト登録者と合格者が見れる。
- My page?

#### 思ったこと
- スライドでプレゼンするだけなら figma で PDF 作るだけでもいいのかも？
- Webページ作って公開するならサーバ必要、、Fire base の無料プランで作る？

**Comment by nafuka11** [comment]
静的ページならGitHub Pagesもありかと思います。

**Comment by tora666** [comment]
#### 疑問点
![image0-1 1](https://user-images.githubusercontent.com/45866095/80509805-d9d5af80-89b4-11ea-86f7-a4f0f7471d05.png)

上の画像のように「しつもんしてみる？」ボタンを押してbot を起動させることは可能？(discordに飛ぶ感じ...?)
web ページからも簡単に質問できたらいいなぁと。

**Comment by nafuka11** [comment]
botが代理で質問投稿するのは可能だと思います。
userが投稿するようにするのは、可能かどうか調査が必要そうです。

**Comment by tora666** [comment]
#### やることリスト

1.  デザインテイスト決め(42っぽさ、ランキングっぽさ、カラー)
2. 最低限の要素で プロトタイプ作る(Figma)　→　メンバーに確認
3. HTML,CSS で実装
--- 
時間に余裕があったら....

4. CSS アニメーション
5. デザイン詰め

**Comment by tora666** [comment]
#### 1. デザインテイスト決め
- 42っぽさ
  - 暗めのカラー
  - ゲーム
  - 宇宙
  - 遊び心
  - インベーダ
<img width="1042" alt="スクリーンショット 2020-04-29 12 42 00" src="https://user-images.githubusercontent.com/45866095/80559021-45e8ff80-8a17-11ea-98e4-dfbec1f2e746.png">

- カラー
  - 濃紺ベース
  - 遊びごころ
<img width="120" alt="スクリーンショット 2020-04-29 13 01 19" src="https://user-images.githubusercontent.com/45866095/80559751-8a759a80-8a19-11ea-9f01-a6dbc7539230.png">

#### 参考
<img width="459" alt="スクリーンショット 2020-04-29 13 11 26" src="https://user-images.githubusercontent.com/45866095/80560175-f3114700-8a1a-11ea-9750-7429ecb3ab60.png">

**Comment by tora666** [comment]
#### デザイン案
- Top page
ご意見ある方お待ちしています！！お気軽に！！

<img width="698" alt="スクリーンショット 2020-04-29 16 51 26" src="https://user-images.githubusercontent.com/45866095/80573316-b1909400-8a3a-11ea-93bd-8b5f3b7be459.png">

- my pageも作りたい、、

**Comment by nafuka11** [comment]
ありがとうございます！デザイン、とても素敵ですね！
ゲームを意識したデザインですごく42っぽいなと思います！
モチベーションが上がるかっこいいデザインだと感じます！

拝見していて全体Rankingだとconcierge感が薄いのかなと感じました。conciergeは個人向けなサービスな気がしてきました。

全体Rankingは1月PiscineにあったようなSpreadsheetを想像していました（URLはDiscordにて）。
Piscine中はそのSpreadsheetを見て他の人の進捗を見て自分の立ち位置を把握していました。
ただ、Spreadsheetには
- 概要の把握が難しい（全体の立ち位置を把握するには情報が多すぎる）
- 質問へは結び付けられない
という2つの課題があります。ので、この2つを解決したいです。

あるいはtop pageは一旦保留にしておいて、User pageを全面に出した方がいいかもしれません。

**Comment by tora666** [comment]
![42concierge_logo](https://user-images.githubusercontent.com/45866095/80767054-f115c800-8b81-11ea-94ae-a6254c3607e7.png)

![web_image](https://user-images.githubusercontent.com/45866095/80767018-d3e0f980-8b81-11ea-9a96-25a5d22fe4ce.png)
